### ISSUE TITLE
Fix FB login error

### ISSUE THREAD

**Issue by repli2dev** [repli2dev/nature-quizzer#7]
PHP Notice: Undefined offset: 1 in /srv/app/www.poznavackaprirody.cz/vendor/facebook/graph-sdk/src/Facebook/Http/GraphRawResponse.php:108

**Comment by harsh414** [comment]
https://stackoverflow.com/questions/53327170/facebook-php-api-throwing-exception-while-login

check if it helps

**Comment by repli2dev** [comment]
@harsh414 Thanks!
